import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import QueryClientContextProvider from "@/providers/react-query.provider";
import { NuqsAdapter } from "nuqs/adapters/next/app";

import { Toaster as SonnerToaster } from "@/components/ui/sonner";

import { Toaster as ShadcnUiToaster } from "@/components/ui/toaster";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ThemeProvider>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased bg-sidebar overflow-x-hidden`}
        >
          <QueryClientContextProvider>
            <SonnerToaster
              toastOptions={{}}
              expand={false}
              position="bottom-right"
              closeButton
              richColors
              visibleToasts={4}
              duration={8000}
            />
            {/** I added this toaster for class-validator errors */}
            <ShadcnUiToaster />
            <NuqsAdapter>{children}</NuqsAdapter>
          </QueryClientContextProvider>
        </body>
      </ThemeProvider>
    </html>
  );
}
